import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Moment WebApp",
  description: "Generated by create next app",
};

export const metadats ={
  icons:{
    icon: '/favicon.svg',
  }
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
